/* Danscaner Pro · módulo que se carga solo cuando se usa */
window.__mods=window.__mods||{};
__mods.pptxRender=async function(ab,onSlide){await loadLib('jszip');const z=await JSZip.loadAsync(ab),P=new DOMParser(),xml=async p=>{const f=z.file(p);return f?P.parseFromString(await f.async('string'),'application/xml'):null};const tag=(n,t)=>[...n.getElementsByTagName(t)];const first=(n,t)=>n.getElementsByTagName(t)[0];const pres=await xml('ppt/presentation.xml');if(!pres)throw new Error('No es un PowerPoint (.pptx) válido');const sz=first(pres,'p:sldSz'),CX=+(sz?.getAttribute('cx')||12192000),CY=+(sz?.getAttribute('cy')||6858000);const rels=await xml('ppt/_rels/presentation.xml.rels'),rmap={};tag(rels,'Relationship').forEach(r=>rmap[r.getAttribute('Id')]=r.getAttribute('Target'));const ids=tag(pres,'p:sldId').map(s=>s.getAttribute('r:id'));const resolve=(base,t)=>{if(t.startsWith('/'))return t.slice(1);const parts=base.split('/');parts.pop();for(const s of t.split('/')){if(s==='..')parts.pop();else if(s!=='.')parts.push(s)}return parts.join('/')};const W=1600,K=W/CX,H=Math.round(CY*K);
for(const [si,id] of ids.entries()){const path=resolve('ppt/presentation.xml',rmap[id]);const sl=await xml(path);if(!sl)continue;const srels=await xml(resolve(path,'_rels/'+path.split('/').pop()+'.rels')),sm={};if(srels)tag(srels,'Relationship').forEach(r=>sm[r.getAttribute('Id')]=r.getAttribute('Target'));const c=canvas(W,H),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);const bgc=first(sl,'p:bg')&&first(first(sl,'p:bg'),'a:srgbClr');if(bgc){x.fillStyle='#'+bgc.getAttribute('val');x.fillRect(0,0,W,H)}let flowY=H*.08;
const xf=n=>{const sp=first(n,'p:spPr')||first(n,'p:xfrm')?.parentNode||n;const o=first(sp,'a:off'),e=first(sp,'a:ext');return o&&e?{x:+o.getAttribute('x')*K,y:+o.getAttribute('y')*K,w:+e.getAttribute('cx')*K,h:+e.getAttribute('cy')*K}:null};
const wrapDraw=(paras,box)=>{let y=box.y+8;for(const p of paras){const lines=[];let fs=18,bold=false,col='#222';const words=[];for(const r of p.runs){fs=r.fs;bold=r.b;col=r.c;for(const w of r.t.split(/(\s+)/))if(w)words.push({w,fs,b:r.b,c:r.c})}const px=(fs*12700*K);const lh=px*1.2;x.font=(bold?'700 ':'')+px+'px Arial, sans-serif';let line='';for(const wd of words){const test=line+wd.w;if(x.measureText(test).width>box.w-16&&line.trim()){lines.push(line);line=wd.w.trimStart()}else line=test}if(line.trim()||!words.length)lines.push(line);x.fillStyle=col;x.textBaseline='top';for(const ln of lines){const tw=x.measureText(ln).width;const lx=p.al==='ctr'?box.x+(box.w-tw)/2:p.al==='r'?box.x+box.w-8-tw:box.x+8;if(p.bul&&ln===lines[0]){x.fillText('•',lx-px*.7,y)}x.fillText(ln,lx,y);y+=lh}}return y};
const paras=tb=>tag(tb,'a:p').map(p=>{const pPr=first(p,'a:pPr');return {al:pPr?.getAttribute('algn'),bul:!!(pPr&&first(pPr,'a:buChar')),runs:tag(p,'a:r').concat(tag(p,'a:fld')).map(r=>{const rp=first(r,'a:rPr'),cl=rp&&first(rp,'a:srgbClr');return {t:tag(r,'a:t').map(t=>t.textContent).join(''),fs:+(rp?.getAttribute('sz')||1800)/100,b:rp?.getAttribute('b')==='1',c:cl?'#'+cl.getAttribute('val'):'#222'}})}});
const walk=async node=>{for(const n of [...node.children]){const nm=n.tagName;if(nm==='p:grpSp'){await walk(n);continue}if(nm==='p:sp'){let b=xf(n);const sp=first(n,'p:spPr');const fill=sp&&[...sp.children].find(k=>k.tagName==='a:solidFill');const fc=fill&&first(fill,'a:srgbClr');const tb=first(n,'p:txBody');const ph=first(n,'p:ph');const hasText=tb&&tag(tb,'a:t').some(t=>t.textContent.trim());if(!b){if(!hasText)continue;const tp=ph?.getAttribute('type')||'';b=/title/i.test(tp)?{x:W*.06,y:H*.05,w:W*.88,h:H*.18}:{x:W*.06,y:Math.max(flowY,H*.25),w:W*.88,h:H*.65}}if(fc){x.fillStyle='#'+fc.getAttribute('val');x.fillRect(b.x,b.y,b.w,b.h)}if(hasText){const ps=paras(tb);if(ph&&/title/i.test(ph.getAttribute('type')||''))ps.forEach(p=>p.runs.forEach(r=>{if(!first(n,'a:rPr')?.getAttribute('sz'))r.fs=Math.max(r.fs,36);r.b=true}));const end=wrapDraw(ps,b);flowY=Math.max(flowY,end)}continue}if(nm==='p:pic'){const b=xf(n),bl=first(n,'a:blip'),rid=bl&&(bl.getAttribute('r:embed'));if(!b||!rid||!sm[rid])continue;const mp=resolve(path,sm[rid]),mf=z.file(mp);if(!mf||/\.(emf|wmf|tiff?)$/i.test(mp))continue;const u=URL.createObjectURL(await mf.async('blob'));try{const im=await loadImg(u);x.drawImage(im,b.x,b.y,b.w,b.h)}catch(e){}finally{URL.revokeObjectURL(u);_imgCache.delete(u)}continue}if(nm==='p:graphicFrame'){const b=xf(n);const rows=tag(n,'a:tr');if(!b||!rows.length)continue;const rh=b.h/rows.length;x.strokeStyle='#999';x.lineWidth=1;rows.forEach((tr,ri)=>{const cells=tag(tr,'a:tc'),cw=b.w/Math.max(1,cells.length);cells.forEach((tc,ci)=>{x.strokeRect(b.x+ci*cw,b.y+ri*rh,cw,rh);const t=tag(tc,'a:t').map(t=>t.textContent).join(' ');const px=Math.min(rh*.45,14*12700*K);x.font=px+'px Arial, sans-serif';x.fillStyle='#222';x.textBaseline='middle';let s=t;while(s&&x.measureText(s).width>cw-10)s=s.slice(0,-1);x.fillText(s,b.x+ci*cw+5,b.y+ri*rh+rh/2)})})}}};
const tree=first(sl,'p:spTree');if(tree)await walk(tree);await onSlide(c,si+1,ids.length,{w:CX/12700,h:CY/12700})}return ids.length}

