/* Danscanner Pro · módulo que se carga solo cuando se usa */
window.__mods=window.__mods||{};
__mods.uiExcelPdf=function(el){let wb=null,file=null,tmr=0,pages=[];
el.innerHTML='<div class="fp"></div><div class="xlopts" hidden><div class="row">'+opt('Hoja','<select class="xsh"></select>')+opt('Tamaño de hoja',sel('xsz',[['a4','A4'],['oficio','Oficio'],['carta','Carta']]))+'</div><div class="row">'+opt('Orientación',sel('xor',[['h','Horizontal'],['v','Vertical']]))+opt('Escala',sel('xfit',[['ancho','Ajustar al ancho'],['pagina','Todo en una página'],['100','100 %'],['custom','Personalizada']]))+'</div><label class="opt xzw" hidden><span>Zoom: <b class="xzv">80</b> %</span><input type="range" class="xz" min="25" max="160" value="80"></label><label class="opt"><span>Márgenes: <b class="xmv">10</b> mm</span><input type="range" class="xm" min="0" max="30" value="10"></label><label class="chk"><input type="checkbox" class="xgrid" checked> Mostrar cuadrícula</label><label class="chk"><input type="checkbox" class="xhead" checked> Repetir la primera fila en cada hoja</label><label class="chk"><input type="checkbox" class="xcen" checked> Centrar en la hoja</label><label class="chk"><input type="checkbox" class="xnum"> Numerar páginas</label><div class="cph">Vista previa <span class="muted xinfo"></span></div><div class="xlprev"><div class="xlpages"></div></div></div><button class="btn pri block run">Generar PDF</button><div class="result"></div>';
const O=()=>({sheet:$('.xsh',el).value,size:$('.xsz',el).value,land:$('.xor',el).value==='h',fit:$('.xfit',el).value,zoom:+$('.xz',el).value,margin:+$('.xm',el).value,grid:$('.xgrid',el).checked,head:$('.xhead',el).checked,center:$('.xcen',el).checked,num:$('.xnum',el).checked});
const layout=()=>{if(!wb)return;const o=O();$('.xmv',el).textContent=o.margin;$('.xzv',el).textContent=o.zoom;$('.xzw',el).hidden=o.fit!=='custom';const names=o.sheet==='*'?wb.SheetNames:[o.sheet];let [w,h]=PAGE_MM[o.size]||PAGE_MM.a4;if(o.land)[w,h]=[h,w];pages=[];for(const nm of names)pages.push(...xlPagesFor(wb.Sheets[nm],nm,w,h,o));pages.forEach((p,i)=>{if(o.num){const f=document.createElement('div');f.className='xlnum';f.textContent=(i+1)+' / '+pages.length;p.appendChild(f)}});const wrap=$('.xlpages',el);wrap.innerHTML='';pages.forEach(p=>{const holder=document.createElement('div');holder.className='xlhold';holder.appendChild(p);wrap.appendChild(holder)});const pw=mm2px(w);wrap.style.zoom=Math.min(1,($('.xlprev',el).clientWidth-24)/pw);$('.xinfo',el).textContent='· '+pages.length+' página(s) · '+w+'×'+h+' mm'};
const relayout=()=>{clearTimeout(tmr);tmr=setTimeout(layout,120)};
filePicker($('.fp',el),{accept:'.xlsx,.xls,.xlsm,.csv,.ods',multi:false,onChange:files=>{file=files[0];wb=null;$('.result',el).innerHTML='';$('.xlopts',el).hidden=!file;if(!file)return;withBusy(async()=>{busy('Leyendo planilla…');await loadLib('xlsx');wb=XLSX.read(await file.arrayBuffer(),{cellDates:true});$('.xsh',el).innerHTML=(wb.SheetNames.length>1?'<option value="*">Todas las hojas</option>':'')+wb.SheetNames.map(n=>'<option>'+esc(n)+'</option>').join('');const ws=wb.Sheets[wb.SheetNames[0]],r=XLSX.utils.decode_range(ws['!ref']||'A1');$('.xor',el).value=(r.e.c-r.s.c)>6?'h':'v';busy(false);layout()})}});
el.addEventListener('input',e=>{if(e.target.closest('.xlopts'))relayout()});el.addEventListener('change',e=>{if(e.target.closest('.xlopts'))relayout()});
new ResizeObserver(()=>{if(wb)relayout()}).observe(el);
$('.run',el).onclick=()=>withBusy(async()=>{if(!wb)return toast('Primero seleccioná una planilla');layout();if(!pages.length)return toast('La hoja está vacía');await loadLib('h2c');await loadLib('pdflib');const pdf=await PDFLib.PDFDocument.create();const host=document.createElement('div');host.className='dxhost';document.body.appendChild(host);const o=O();let [w,h]=PAGE_MM[o.size]||PAGE_MM.a4;if(o.land)[w,h]=[h,w];
try{for(const [i,p] of pages.entries()){busy('Generando página '+(i+1)+'/'+pages.length);const cl=p.cloneNode(true);host.innerHTML='';host.appendChild(cl);const c=await html2canvas(cl,{scale:2,backgroundColor:'#ffffff',logging:false});await canvasToPdfPage(pdf,c,w*72/25.4,h*72/25.4)}}finally{host.remove()}
busy(false);showResults($('.result',el),[{blob:pdfBlob(await pdf.save()),name:baseName(file)+'.pdf',note:pages.length+' página(s) · '+o.size.toUpperCase()+' '+(o.land?'horizontal':'vertical')+' · márgenes '+o.margin+' mm'}])})}
function xlPagesFor(ws,name,wmm,hmm,o){if(!ws||!ws['!ref'])return[];const html=(XLSX.utils.sheet_to_html(ws).match(/<table[\s\S]*<\/table>/i)||[''])[0];if(!html)return[];
const meas=document.createElement('div');meas.className='dxhost';meas.innerHTML=html;document.body.appendChild(meas);const table=meas.querySelector('table');table.className='xltab'+(o.grid?' grid':'');
const cols=ws['!cols'];if(cols&&cols.length){const cg=document.createElement('colgroup');const r=XLSX.utils.decode_range(ws['!ref']);for(let c=r.s.c;c<=r.e.c;c++){const cc=cols[c]||{};const px=cc.wpx||(cc.wch?cc.wch*7+10:(cc.width?cc.width*7:0));const col=document.createElement('col');if(px)col.style.width=px+'px';if(cc.hidden)col.style.visibility='collapse';cg.appendChild(col)}table.prepend(cg)}
const rowsMeta=ws['!rows'];const rows=[...table.rows];if(rowsMeta)rows.forEach((tr,i)=>{const m=rowsMeta[i];if(m&&m.hpx)tr.style.height=m.hpx+'px';if(m&&m.hidden)tr.style.visibility='collapse'});
const Tw=table.offsetWidth,rowH=rows.map(r=>r.offsetHeight),totalH=rowH.reduce((a,b)=>a+b,0);meas.remove();
const pageW=mm2px(wmm),pageH=mm2px(hmm),m=mm2px(o.margin),cw=pageW-2*m,ch=pageH-2*m-(o.num?14:0);
let s=o.fit==='ancho'?Math.min(2.2,cw/Tw):o.fit==='pagina'?Math.min(2.2,cw/Tw,ch/totalH):o.fit==='100'?1:o.zoom/100;
const avail=ch/s,headH=o.head&&rows.length>1?rowH[0]:0;const groups=[];let cur=[],hh=0;
for(let i=0;i<rows.length;i++){if(cur.length&&hh+rowH[i]>avail&&!(o.head&&cur.length===1&&cur[0]===0&&i===1)){groups.push(cur);cur=[];hh=0;if(headH&&i>0){cur.push(0);hh=headH}}cur.push(i);hh+=rowH[i]}if(cur.length)groups.push(cur);
return groups.map(idx=>{const pg=document.createElement('div');pg.className='xlpage';pg.style.cssText='width:'+pageW+'px;height:'+pageH+'px;padding:'+m+'px';const inner=document.createElement('div');const offX=o.center?Math.max(0,(cw-Tw*s)/2):0;inner.style.cssText='width:'+Tw+'px;transform:scale('+s+');transform-origin:0 0;margin-left:'+offX+'px';const tb=table.cloneNode(true);const set=new Set(idx);[...tb.rows].forEach((r,k)=>{if(!set.has(k))r.style.visibility='collapse'});inner.appendChild(tb);pg.appendChild(inner);return pg})}


